### ISSUE TITLE
attribute constraint in application_information

### ISSUE THREAD

**Issue by dibyendujana** [energyos/OpenESPI-Common-java#189]
for all attributes of application information have - minOccurs=0 in schema definition and table column definition is Null. Is it intended? or some constraint can be defined for this.
-

**Comment by MartyBurns** [comment]
General comments on schema validation:

There are many styles of xsd and UML modeling in use in various information exchange domains. The ESPI standard schema was built with all optional fields. So, as we refined the xsd for ApplicationInformation and authorization we kept this model. 

Clearly interoperability with all optional fields doesn't mean much. So, where are the actual interoperability agreements and how is it tested?

It turns out there are two types of content testing that need to be performed. The first is "type" testing where each element that is present is tested for its composition according to its type definition -- this is typically done with schema validation in XML documents.

The second is referential testing. That is, if the file has "this" it must also have "that" or "that" must contain a specific value(s). Such testing is not practical with schema validation alone. Hence, additional tools are necessary. Schematron, which is a "short hand" xml vocabulary for using the XPath standard query language for XML documents can be used for referential testing. The Green Button certification tests use this method extensively. Additionally, tests can simply verify the presence or absence of a list of required elements.
 
We use schema validation for type and multiplicity validation and use the other tools to go beyond that. This why the required is enforced in the implementation agreement and the test and not in the schema. To find the definitive definitions of interoperability for Green Button, the OpenADE task force is assembling GreenButtonTestPlan and corresponding GreenButtonTestCases.xlsm document (http://www.greenbuttondata.org/library/#testing). 

Additional documentation hopefully will be made available in the future.

Recommend this issue be closed.

**Comment by jateeter** [comment]
I find both the GreenButtonTestPlan and the GreenButtonTestCases.xlsm (referenced above) to be too opaque with respect to the documentation of the articulation of specific required elements. 

Is there a way to make this information more accessible?  If not in the .xsd (where all might find it easily), then in a specific (maybe separate) document for ease of access?  I really would not know where to look in the two referenced docuemnts and, not knowing where to look, would quite likely not know what is, and is not, a required attribute of any of our ESPI resources.

**Comment by MartyBurns** [comment]
Based on discussions on this week's OpenESPI call, there was a strong consensus that at least for ApplicationInformation and probably Authorization required fields should have a corresponding multiplicity of 1 in the schema. We will confirm on the OpenADE call tomorrow, January 6th, and accordingly we will make the update to the schema.

We will document the final set of required fields in this message thread before closing.

**Comment by MartyBurns** [comment]
Updated schema commit 900d5a7079970481c7c2a9dcb20daa22d38b171a
